var ingredientList = [
  "Sweet Vermouth",
  "Orange bitters",
  "Dry Vermouth",
  "Tea",
  "Bitters",
  "Sugar",
  "demerara Sugar",
  "Dubonnet Rouge",
  "Lime juice",
  "Carbonated water",
  "Grenadine",
  "Grapefruit juice",
  "Apple juice",
  "Pineapple juice",
  "Lemon juice",
  "Sugar syrup",
  "Milk",
  "Strawberries",
  "Chocolate syrup",
  "Yogurt",
  "Mango",
  "Ginger",
  "Lime",
  "Cantaloupe",
  "Berries",
  "Grapes",
  "Kiwi",
  "Tomato juice",
  "Cocoa powder",
  "Chocolate",
  "Heavy cream",
  "Galliano",
  "Coffee",
  "Water",
  "Espresso",
  "Angelica root",
  "Orange",
  "Cranberries",
  "Apple cider",
  "Cranberry juice",
  "Egg yolk",
  "Egg",
  "Grape juice",
  "Peach nectar",
  "Lemon",
  "Lemonade",
  "Cider",
  "Sprite",
  "7-Up"
];
var alcoholList = [
  "Light rum",
  "Applejack",
  "Gin",
  "Dark rum",
  "Strawberry schnapps",
  "Scotch",
  "Apricot brandy",
  "Triple sec",
  "Southern Comfort",
  "Brandy",
  "Lemon vodka",
  "Blended whiskey",
  "Amaretto",
  "Champagne",
  "Coffee liqueur",
  "Bourbon",
  "Tequila",
  "Vodka",
  "Añejo rum",
  "Kahlua",
  "Dubonnet Rouge",
  "Irish whiskey",
  "Apple brandy",
  "Cherry brandy",
  "Creme de Cacao",
  "Port",
  "Coffee brandy",
  "Red wine",
  "Rum",
  "Ricard",
  "Sherry",
  "Cognac",
  "Sloe gin",
  "Galliano",
  "Peach Vodka",
  "Ouzo",
  "Spiced rum",
  "Johnnie Walker",
  "Everclear",
  "Firewater",
  "Lager",
  "Whiskey",
  "Absolut Citron",
  "Pisco",
  "Irish cream",
  "Ale",
  "Chocolate liqueur",
  "Midori melon liqueur",
  "Sambuca",
  "Blackberry brandy",
  "Peppermint schnapps",
  "Creme de Cassis",
  "Jack Daniels"
];

$(document).ready(function() {
  function searchIngredient(ingredient) {
    var queryUrl =
      "https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=" + ingredient;

    $.ajax({
      url: queryUrl,
      method: "GET"
    }).then(function(response) {
      console.log(response);
    });
  }
  $("#searchBtn").on("click", function() {
    var ingredient = $("#userIngredient").val();
    searchIngredient(ingredient);
  });
});
